### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by NightScript370** [RoadrunnerWMC/Reggie-Next-2#3]
What's the difference between the 2 reggie next repos?

**Comment by RoadrunnerWMC** [comment]
Reggie Next 1 is the original Reggie plus tons of additions and improvements. Reggie Next 2 is an unfinished attempt to rewrite it in a way that would allow it to become compatible with more games (and also to add some features that would be very difficult to implement in the original Reggie). RN2 isn't really usable for anything.

**Comment by aboood40091** [comment]
Will you ever continue working on it though?

**Comment by RoadrunnerWMC** [comment]
Maybe someday? I do still like the concept.

**Comment by aboood40091** [comment]
Good luck then. 🖒
